'use server';

/**
 * @fileOverview Generates voice responses from 'El Súper' based on player voice commands.
 *
 * - generateVoiceResponse - A function that generates the voice response.
 * - VoiceResponseInput - The input type for the generateVoiceResponse function.
 * - VoiceResponseOutput - The return type for the generateVoiceResponse function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const VoiceResponseInputSchema = z.object({
  command: z.string().describe('The voice command spoken by the player.'),
});
export type VoiceResponseInput = z.infer<typeof VoiceResponseInputSchema>;

const VoiceResponseOutputSchema = z.object({
  response: z.string().describe('The voice response generated by El Súper.'),
});
export type VoiceResponseOutput = z.infer<typeof VoiceResponseOutputSchema>;

export async function generateVoiceResponse(input: VoiceResponseInput): Promise<VoiceResponseOutput> {
  return generateVoiceResponseFlow(input);
}

const voiceResponsePrompt = ai.definePrompt({
  name: 'voiceResponsePrompt',
  input: {
    schema: z.object({
      command: z.string().describe('The voice command spoken by the player.'),
    }),
  },
  output: {
    schema: z.object({
      response: z.string().describe('The voice response generated by El Súper in a funny, theatrical, and slightly acid tone.'),
    }),
  },
  prompt: `You are the voice of 'El Súper', a character in a reality show inspired by Gran Hermano. You are funny, theatrical, acid but friendly, and have a big ego.

  Generate a voice response to the following player command:

  Command: {{{command}}}

  Remember to always speak in the first person and to be theatrical.  If someone tells you something try to pry for more information.  Never be gratuitously rude.
  Also, remember the recurring phrase: "No olvidéis que yo lo veo TODO."`,
});

const generateVoiceResponseFlow = ai.defineFlow<
  typeof VoiceResponseInputSchema,
  typeof VoiceResponseOutputSchema
>(
  {
    name: 'generateVoiceResponseFlow',
    inputSchema: VoiceResponseInputSchema,
    outputSchema: VoiceResponseOutputSchema,
  },
  async input => {
    const {output} = await voiceResponsePrompt(input);
    return output!;
  }
);
